export const CHANGE_SCREEN = "CHANGE_SCREEN";
export const CHANGE_PREVIOUS_SCREEN = "CHANGE_PREVIOUS_SCREEN"; 
export const REPLACE_SCREEN = "REPLACE_SCREEN";

// AUTH ACTIONS

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const LOGIN_INITIALIZE = "LOGIN_INITIALIZE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_MOCK = "LOGIN_MOCK";

export const SIGNUP_INITIALIZE = "SIGNUP_INITIALIZE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const RESET_PASSWORD = "RESET_PASSWORD";

// SCHEDULE ACTIONS
export const SCHEDULE_CREATE = "SCHEDULE_CREATE";
export const SCHEDULE_CREATE_SUCCESS = "SCHEDULE_CREATE_SUCCESS";
export const SCHEDULE_CREATE_FAIL = "SCHEDULE_CREATE_FAIL";

export const SCHEDULE_UPDATE = "SCHEDULE_UPDATE";
export const SCHEDULE_UPDATE_SUCCESS = "SCHEDULE_UPDATE_SUCCESS";

export const SCHEDULE_FETCH_HOME = "SCHEDULE_FETCH_HOME";
export const SCHEDULE_FETCH_HOME_SUCCESS = "SCHEDULE_FETCH_HOME_SUCCESS";
export const SCHEDULE_FETCH_HOME_FAIL = "SCHEDULE_FETCH_HOME_FAIL"; 

export const FETCH_SCHEDULE = "FETCH_SCHEDULE";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAIL = "FETCH_SCHEDULE";

export const BOOK_SCHEDULE = "BOOK_SCHEDULE";
export const BOOK_SCHEDULE_SUCCESS = "BOOK_SCHEDULE_SUCCESS";

export const UNBOOK_SCHEDULE = "UNBOOK_SCHEDULE";
export const UNBOOK_SCHEDULE_SUCCESS = "UNBOOK_SCHEDULE_SUCCESS";

export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS";

export const REMOVE_SCHEDULE = "REMOVE_SCHEDULE"; // Don't use this if possible

export const CANCEL_SCHEDULE = "CANCEL_SCHEDULE";
export const CANCEL_SCHEDULE_SUCCESS = "CANCEL_SCHEDULE_SUCCESS";

// User ACTIONS

export const SET_USER_INFO = "SET_USER_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";

export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS"; 

export const ADD_USER_REVIEW = 'ADD_USER_REVIEW';
export const ADD_USER_REVIEW_SUCCESS = 'ADD_USER_REVIEW_SUCCESS';

export const FETCH_USER_REVIEWS = 'FETCH_USER_REVIEWS';
export const FETCH_USER_REVIEWS_SUCCESS = 'FETCH_USER_REVIEWS_SUCCESS';

export const FOLLOW_USER = 'FOLLOW_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS'

export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS'

// CHATROOM ACTIONS

export const FETCH_CHATROOMS = "FETCH_CHATROOMS";
export const FETCH_CHATROOMS_SUCCESS = "FETCH_CHATROOMS_SUCCESS";

export const UPDATE_CHATROOMS = "UPDATE_CHATROOMS";

export const OPEN_CHAT = "OPEN_CHAT";

export const CHATROOM_CREATE = "CHATROOM_CREATE";
export const CHATROOM_CREATE_SUCCESS = "CHATROOM_CREATE_SUCCESS";

// export const UPDATE_USER_ROOMS = "UPDATE_USER_ROOMS";
// export const UPDATE_USER_ROOMS_SUCCESS = "UPDATE_USER_ROOMS_SUCCESS";
// export const FETCH_ROOM = "FETCH_ROOM";
// export const FETCH_ROOM_SUCCESS = "FETCH_ROOM_SUCCESS";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const FETCH_MESSAGES_SUCCESS = "FETCH_MESSAGES_SUCCESS";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";

