export const CHANGE_SCREEN = "CHANGE_SCREEN";

export const LOGIN_EMAIL = "LOGIN_EMAIL";
export const LOGOUT = "LOGOUT";

export const LOGIN_INITIALIZE = "LOGIN_INITIALIZE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_MOCK = "LOGIN_MOCK";

export const SIGNUP_INITIALIZE = "SIGNUP_INITIALIZE";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

//schedule form action types
export const SCHEDULE_CREATE = "SCHEDULE_CREATE";
export const SCHEDULE_CREATE_SUCCESS = "SCHEDULE_CREATE_SUCCESS";
export const SCHEDULE_CREATE_FAIL = "SCHEDULE_CREATE_FAIL";
// export const SCHEDULE_FETCH = "SCHEDULE_FETCH";

export const SCHEDULE_FETCH_HOME = "SCHEDULE_FETCH_HOME";
export const SCHEDULE_FETCH_HOME_SUCCESS = "SCHEDULE_FETCH_HOME_SUCCESS";
export const SCHEDULE_FETCH_HOME_FAIL = "SCHEDULE_FETCH_HOME_FAIL"; 
